// Package synth implements Phase 3 of #268: derive a per-agent state
// classifier (ruleset.json) and interactive driver protocol
// (driver_protocol.json) from a recording's signals.jsonl +
// ground_truth.jsonl. Contradictions surface as synthesis_conflicts.json.
//
// The synthesizer is intentionally simple — a greedy compositor over
// candidate rules generated by inspecting signals near each labeled
// transition. ML / learned classifiers are explicitly out of scope per
// the issue.
package synth

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"irrlicht/tools/agent-onboarding/internal/groundtruth"
	"irrlicht/tools/agent-onboarding/internal/rulelib"
)

// Signal mirrors sensors.Signal but lives in this package to keep synth
// independent of the recorder's binary build.
type Signal struct {
	Ts      time.Time       `json:"ts"`
	Sensor  string          `json:"sensor"`
	Kind    string          `json:"kind"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// Ruleset is the synthesized classifier — emitted to ruleset.json.
type Ruleset struct {
	SchemaVersion int            `json:"schema_version"`
	Agent         string         `json:"agent"`
	GeneratedAt   time.Time      `json:"generated_at"`
	Rules         []rulelib.Rule `json:"rules"`
}

// DriverProtocol carries the per-agent interactive contract discovered
// from probe runs.
type DriverProtocol struct {
	SchemaVersion       int    `json:"schema_version"`
	Agent               string `json:"agent"`
	TrustDialogKeys     string `json:"trust_dialog_keys,omitempty"`   // e.g. "1<Enter>"
	ReadinessSignal     string `json:"readiness_signal,omitempty"`    // substring on pane that appears once
	TurnDoneSignal      string `json:"turn_done_signal,omitempty"`    // field=value or substring
	InterruptKey        string `json:"interrupt_key,omitempty"`       // "Escape" | "C-c" | "C-d"
	TypingRhythmMinMs   int    `json:"typing_rhythm_min_ms,omitempty"` // min gap between keystrokes
	InterruptAckMarker  string `json:"interrupt_ack_marker,omitempty"`
}

// Conflict is one unresolved synthesis point — a labeled timeline
// position where no candidate rule fired (or where two rules disagreed).
type Conflict struct {
	Marker          string `json:"marker"`
	TsOffsetMs      int    `json:"ts_offset_ms"`
	ExpectedState   string `json:"expected_state"`
	WhyUnresolved   string `json:"why_unresolved"`
	NearbySignalIDs []int  `json:"nearby_signal_indices,omitempty"`
}

// ConflictReport is emitted to synthesis_conflicts.json.
type ConflictReport struct {
	SchemaVersion int        `json:"schema_version"`
	Agent         string     `json:"agent"`
	Scenario      string     `json:"scenario"`
	GeneratedAt   time.Time  `json:"generated_at"`
	Conflicts     []Conflict `json:"conflicts"`
}

// Input bundles what the synthesizer needs to run on one scenario.
type Input struct {
	Agent       string
	Scenario    string
	SignalsPath string // signals.jsonl
	GroundTruth string // ground_truth.jsonl
	StagingDir  string // .build/agent-onboarding/staged/<agent>/
}

// Run executes synthesis end-to-end:
//
//	read signals + ground_truth → generate candidate rules → greedy compose →
//	detect driver protocol → write ruleset.json, driver_protocol.json,
//	synthesis_conflicts.json into staging.
func Run(ctx context.Context, in Input) error {
	if in.Agent == "" || in.SignalsPath == "" || in.GroundTruth == "" || in.StagingDir == "" {
		return fmt.Errorf("synth: agent, signals path, ground-truth path, and staging dir are required")
	}
	if err := os.MkdirAll(in.StagingDir, 0o755); err != nil {
		return err
	}

	signals, err := readSignals(in.SignalsPath)
	if err != nil {
		return fmt.Errorf("read signals: %w", err)
	}
	meta, labels, err := readGroundTruth(in.GroundTruth)
	if err != nil {
		return fmt.Errorf("read ground-truth: %w", err)
	}
	// Anchor labels against meta.RecordingStartedAt when available — labels
	// are authored relative to wall-clock recording start, NOT to the
	// first signal's arrival (which may lag by hundreds of ms depending
	// on sensor cadence). Fall back to signals[0].Ts only when meta is
	// zero, e.g. for a recording that predates the multi-sensor recorder.
	rules, conflicts := greedyCompose(signals, labels, meta.RecordingStartedAt)
	protocol := derivedProtocol(in.Agent, signals)

	if err := writeJSON(filepath.Join(in.StagingDir, "ruleset.json"), Ruleset{
		SchemaVersion: 1, Agent: in.Agent, GeneratedAt: time.Now().UTC(), Rules: rules,
	}); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(in.StagingDir, "driver_protocol.json"), protocol); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(in.StagingDir, "synthesis_conflicts.json"), ConflictReport{
		SchemaVersion: 1, Agent: in.Agent, Scenario: in.Scenario, GeneratedAt: time.Now().UTC(), Conflicts: conflicts,
	}); err != nil {
		return err
	}
	return nil
}

// greedyCompose is the heart of synthesis. For each ground-truth label,
// it scans signals within the tolerance window around the label's
// ts_offset_ms (measured from anchor) and picks the most specific rule
// that fires consistently with the expected state. If nothing fires,
// the label becomes a Conflict.
//
// anchor is the recording's wall-clock start (from
// ground_truth.jsonl's meta.recording_started_at). If zero, falls back
// to signals[0].Ts — older recordings without meta still produce
// usable (if drift-prone) anchors.
func greedyCompose(signals []Signal, labels []groundtruth.Label, anchor time.Time) ([]rulelib.Rule, []Conflict) {
	if len(signals) == 0 {
		return nil, allConflicts(labels, "no signals.jsonl entries")
	}
	startTs := anchor
	if startTs.IsZero() {
		startTs = signals[0].Ts
	}
	var rules []rulelib.Rule
	var conflicts []Conflict
	seen := map[string]bool{}
	priority := 0

	for _, l := range labels {
		tol := l.ToleranceMs
		if tol == 0 {
			tol = 1000
		}
		windowStart := startTs.Add(time.Duration(l.TsOffsetMs-tol) * time.Millisecond)
		windowEnd := startTs.Add(time.Duration(l.TsOffsetMs+tol) * time.Millisecond)
		var nearby []int
		for i, s := range signals {
			if s.Ts.Before(windowStart) || s.Ts.After(windowEnd) {
				continue
			}
			nearby = append(nearby, i)
		}
		if len(nearby) == 0 {
			conflicts = append(conflicts, Conflict{
				Marker: l.Marker, TsOffsetMs: l.TsOffsetMs, ExpectedState: l.ExpectedState,
				WhyUnresolved: "no signals fell within tolerance window",
			})
			continue
		}
		// Propose candidates from nearby signals.
		cand := proposeCandidates(signals, nearby, l.ExpectedState)
		if len(cand) == 0 {
			conflicts = append(conflicts, Conflict{
				Marker: l.Marker, TsOffsetMs: l.TsOffsetMs, ExpectedState: l.ExpectedState,
				WhyUnresolved: "no signal in window produced a candidate rule", NearbySignalIDs: nearby,
			})
			continue
		}
		// Pick the first candidate (deterministic ordering by proposeCandidates).
		best := cand[0]
		best.RuleID = fmt.Sprintf("%s-%d-%s", best.Kind, priority, sanitize(l.Marker))
		best.Priority = priority
		priority++
		// Dedupe by (Kind, Params) so adjacent labels with identical
		// patterns produce one rule, not many.
		k := best.Kind + "|" + string(best.Params)
		if !seen[k] {
			rules = append(rules, best)
			seen[k] = true
		}
	}
	return rules, conflicts
}

// proposeCandidates inspects the signals at indices `nearby` and proposes
// rules that, if fired, would imply the targetState. Returned in priority
// order (most specific first).
func proposeCandidates(signals []Signal, nearby []int, targetState string) []rulelib.Rule {
	var out []rulelib.Rule
	for _, i := range nearby {
		s := signals[i]
		switch s.Sensor {
		case "transcript":
			if s.Kind != "line" {
				continue
			}
			var pl struct {
				Line string `json:"line"`
			}
			if err := json.Unmarshal(s.Payload, &pl); err != nil {
				continue
			}
			// Try to parse the line as JSON and propose a transcript_field_value
			// rule on common done/working markers.
			var obj map[string]any
			if err := json.Unmarshal([]byte(pl.Line), &obj); err == nil {
				if v, ok := obj["stop_reason"].(string); ok {
					out = append(out, mkRule(rulelib.KindTranscriptFieldValue, targetState, map[string]string{"field": "stop_reason", "value": v}))
				}
				if em, ok := obj["event_msg"].(map[string]any); ok {
					if t, ok := em["type"].(string); ok {
						out = append(out, mkRule(rulelib.KindTranscriptFieldValue, targetState, map[string]string{"field": "event_msg.type", "value": t}))
					}
				}
				if k, ok := obj["kind"].(string); ok {
					out = append(out, mkRule(rulelib.KindTranscriptEventKind, targetState, map[string]string{"event_kind": k}))
				}
			}
			// Interrupt marker.
			if strings.Contains(pl.Line, "[Request interrupted by user]") {
				out = append(out, mkRule(rulelib.KindInterruptMarker, targetState, map[string]string{"marker_substring": "[Request interrupted by user]"}))
			}
		case "proc":
			if s.Kind != "spawn" {
				continue
			}
			var pl struct {
				Args []string `json:"args"`
			}
			if err := json.Unmarshal(s.Payload, &pl); err != nil {
				continue
			}
			if len(pl.Args) > 0 {
				out = append(out, mkRule(rulelib.KindProcessSpawned, targetState, map[string]string{"name_pattern": "^" + regexp.QuoteMeta(pl.Args[0])}))
			}
		case "pane":
			if s.Kind != "snapshot" {
				continue
			}
			// Use the SHA prefix as a sentinel; less useful than a substring,
			// but a stable per-snapshot rule.
			var pl struct {
				Snapshot string `json:"snapshot"`
			}
			if err := json.Unmarshal(s.Payload, &pl); err != nil {
				continue
			}
			lines := strings.Split(pl.Snapshot, "\n")
			if len(lines) > 0 {
				out = append(out, mkRule(rulelib.KindPaneSubstringPresent, targetState, map[string]string{"substring": firstNonEmpty(lines)}))
			}
		}
	}
	return out
}

func mkRule(kind, state string, params any) rulelib.Rule {
	b, _ := json.Marshal(params)
	return rulelib.Rule{Kind: kind, TargetState: state, Params: b}
}

// derivedProtocol applies simple heuristics over the signals to fill the
// DriverProtocol fields. This is a starting point; real-world synthesis
// would iterate.
func derivedProtocol(agent string, signals []Signal) DriverProtocol {
	p := DriverProtocol{SchemaVersion: 1, Agent: agent}
	// Trust dialog: look for "Trust" or "Do you trust" substring on a pane
	// snapshot in the first 5 seconds. If found, default the answer.
	for _, s := range signals {
		if s.Sensor != "pane" || s.Kind != "snapshot" {
			continue
		}
		var pl struct {
			Snapshot string `json:"snapshot"`
		}
		if err := json.Unmarshal(s.Payload, &pl); err != nil {
			continue
		}
		if strings.Contains(pl.Snapshot, "Do you trust") || strings.Contains(pl.Snapshot, "Trust this folder") {
			p.TrustDialogKeys = "1<Enter>"
			break
		}
	}
	// Readiness: the first pane snapshot that mentions a prompt-like glyph (>, ❯, $).
	for _, s := range signals {
		if s.Sensor != "pane" {
			continue
		}
		var pl struct {
			Snapshot string `json:"snapshot"`
		}
		if err := json.Unmarshal(s.Payload, &pl); err != nil {
			continue
		}
		if strings.ContainsAny(pl.Snapshot, "❯>$") {
			p.ReadinessSignal = "prompt glyph (❯|>|$) visible"
			break
		}
	}
	// Turn-done: prefer transcript_field_value if any line carries
	// stop_reason or event_msg.type.
	for _, s := range signals {
		if s.Sensor != "transcript" {
			continue
		}
		var pl struct {
			Line string `json:"line"`
		}
		if err := json.Unmarshal(s.Payload, &pl); err != nil {
			continue
		}
		if strings.Contains(pl.Line, `"stop_reason":"end_turn"`) {
			p.TurnDoneSignal = `stop_reason == "end_turn"`
			break
		}
		if strings.Contains(pl.Line, `"event_msg":{"type":"task_complete"}`) {
			p.TurnDoneSignal = `event_msg.type == "task_complete"`
			break
		}
	}
	// Interrupt key default — agents we've seen handle Escape.
	p.InterruptKey = "Escape"
	// Typing rhythm — codex needs 300ms gap. We can't infer this from
	// recorded signals alone; default to a safe 100ms.
	p.TypingRhythmMinMs = 100
	return p
}

func readSignals(path string) ([]Signal, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var out []Signal
	dec := json.NewDecoder(bufio.NewReader(f))
	for {
		var s Signal
		if err := dec.Decode(&s); err != nil {
			if err == io.EOF {
				return out, nil
			}
			return out, err
		}
		out = append(out, s)
	}
}

func readGroundTruth(path string) (groundtruth.Meta, []groundtruth.Label, error) {
	f, err := os.Open(path)
	if err != nil {
		return groundtruth.Meta{}, nil, err
	}
	defer f.Close()
	return groundtruth.Read(f)
}

func writeJSON(path string, v any) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc.Encode(v)
}

func allConflicts(labels []groundtruth.Label, why string) []Conflict {
	out := make([]Conflict, 0, len(labels))
	for _, l := range labels {
		out = append(out, Conflict{
			Marker: l.Marker, TsOffsetMs: l.TsOffsetMs, ExpectedState: l.ExpectedState,
			WhyUnresolved: why,
		})
	}
	return out
}

func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '-' || r == '_':
			b.WriteRune(r)
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return b.String()
}

func firstNonEmpty(lines []string) string {
	for _, l := range lines {
		s := strings.TrimSpace(l)
		if s != "" {
			return s
		}
	}
	return ""
}


