package codegen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"irrlicht/tools/agent-onboarding/internal/groundtruth"
	"irrlicht/tools/agent-onboarding/internal/synth"
)

func TestGenerate_endToEndEmitsCompilableAdapter(t *testing.T) {
	// 1. Stage a tiny synth output by running synth on a synthetic corpus.
	stage := filepath.Join(t.TempDir(), "stage")
	if err := os.MkdirAll(stage, 0o755); err != nil {
		t.Fatal(err)
	}
	prepareSeed(t, stage)

	// 2. Run codegen against the staged outputs.
	adapterDir := filepath.Join(t.TempDir(), "adapter")
	driverDir := filepath.Join(t.TempDir(), "driver")
	err := Generate(Input{
		Agent: "toyagent", StagingDir: stage,
		AdapterOutDir: adapterDir, DriverOutDir: driverDir,
		DisplayName: "Toy Agent", ProcessName: "toyagent",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// 3. Assert the expected files exist.
	expected := []string{
		filepath.Join(adapterDir, "agent.go"),
		filepath.Join(adapterDir, "parser.go"),
		filepath.Join(adapterDir, "pid.go"),
		filepath.Join(adapterDir, "classifier_rules.go"),
		filepath.Join(adapterDir, "parser_test.go"),
		filepath.Join(driverDir, "drive-toyagent-interactive.sh"),
	}
	for _, f := range expected {
		st, err := os.Stat(f)
		if err != nil {
			t.Errorf("missing %s: %v", f, err)
			continue
		}
		if st.Size() == 0 {
			t.Errorf("empty file: %s", f)
		}
	}

	// 4. Sanity-check headers + content.
	b, err := os.ReadFile(filepath.Join(adapterDir, "agent.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "Code generated by agent-onboard gen. DO NOT EDIT.") {
		t.Error("missing generated header in agent.go")
	}
	if !strings.Contains(string(b), `AdapterName = "toyagent"`) {
		t.Errorf("agent.go missing AdapterName const:\n%s", b)
	}

	// 5. Driver script is executable.
	st, _ := os.Stat(filepath.Join(driverDir, "drive-toyagent-interactive.sh"))
	if st != nil && st.Mode().Perm()&0o111 == 0 {
		t.Error("driver script not executable")
	}
}

// prepareSeed writes a tiny signals.jsonl + ground_truth.jsonl, runs synth,
// and leaves ruleset.json + driver_protocol.json in stage/.
func prepareSeed(t *testing.T, stage string) {
	t.Helper()
	dir := filepath.Dir(stage)
	signals := filepath.Join(dir, "signals.jsonl")
	gt := filepath.Join(dir, "ground_truth.jsonl")

	startTime := time.Date(2026, 5, 14, 12, 0, 0, 0, time.UTC)
	// One signal: a transcript line with stop_reason=end_turn.
	signalsContent := `{"ts":"2026-05-14T12:00:00Z","sensor":"transcript","kind":"line","payload":{"line":"{\"stop_reason\":\"end_turn\"}"}}` + "\n"
	if err := os.WriteFile(signals, []byte(signalsContent), 0o644); err != nil {
		t.Fatal(err)
	}

	meta := groundtruth.Meta{SchemaVersion: 1, Agent: "toyagent", Scenario: "test", RecordingStartedAt: startTime}
	labels := []groundtruth.Label{
		{TsOffsetMs: 0, Marker: "done", ExpectedState: "ready", ToleranceMs: 1000},
	}
	f, _ := os.Create(gt)
	groundtruth.Write(f, meta, labels)
	f.Close()

	if err := synth.Run(context.Background(), synth.Input{
		Agent: "toyagent", Scenario: "test",
		SignalsPath: signals, GroundTruth: gt, StagingDir: stage,
	}); err != nil {
		t.Fatalf("synth setup: %v", err)
	}
}
