// Package codegen produces a per-agent Go adapter package and an
// interactive driver script from the synthesizer's outputs
// (ruleset.json + driver_protocol.json + transcript_schema.json — the
// last reserved for future use).
//
// Outputs are written under core/adapters/inbound/agents/<name>/ for Go
// files and .claude/skills/ir:onboard-agent/scripts/ for the driver
// script. Every generated file carries the header
//
//	// Code generated by agent-onboard gen. DO NOT EDIT.
//
// so reviewers can ignore them with git's diff/grep filters.
package codegen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"irrlicht/tools/agent-onboarding/internal/synth"
)

// Input bundles the synthesis outputs codegen consumes.
type Input struct {
	Agent          string
	StagingDir     string // contains ruleset.json + driver_protocol.json
	AdapterOutDir  string // typically core/adapters/inbound/agents/<agent>/
	DriverOutDir   string // typically .claude/skills/ir:onboard-agent/scripts/
	DisplayName    string // human-readable label; defaults to titlecase of agent
	ProcessName    string // for ProcessName const; defaults to agent
	TranscriptPath string // file extension hint for the parser; defaults to .jsonl
}

// Generate emits the adapter Go files and the interactive driver script.
//
// Files written under AdapterOutDir:
//
//	agent.go             — `Agent()` returning agent.Agent declaration
//	parser.go            — minimal TranscriptParser implementation
//	pid.go               — DiscoverPID via process name
//	classifier_rules.go  — exported ClassifierRules() returning []services.ClassifierRule
//	parser_test.go       — round-trip smoke test
//
// Files written under DriverOutDir:
//
//	drive-<agent>-interactive.sh — driver protocol from synthesis
func Generate(in Input) error {
	if in.Agent == "" || in.StagingDir == "" || in.AdapterOutDir == "" || in.DriverOutDir == "" {
		return errors.New("codegen: agent, staging, adapter out, driver out are required")
	}

	rs, err := readRuleset(filepath.Join(in.StagingDir, "ruleset.json"))
	if err != nil {
		return fmt.Errorf("read ruleset: %w", err)
	}
	dp, err := readProtocol(filepath.Join(in.StagingDir, "driver_protocol.json"))
	if err != nil {
		return fmt.Errorf("read driver_protocol: %w", err)
	}

	displayName := in.DisplayName
	if displayName == "" {
		displayName = strings.ToUpper(in.Agent[:1]) + in.Agent[1:]
	}
	processName := in.ProcessName
	if processName == "" {
		processName = in.Agent
	}

	if err := os.MkdirAll(in.AdapterOutDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(in.DriverOutDir, 0o755); err != nil {
		return err
	}

	data := struct {
		Agent          string
		PackageName    string
		DisplayName    string
		ProcessName    string
		GeneratedAt    string
		RulesetJSON    string
		ProtocolJSON   string
		HasReadiness   bool
		HasTurnDone    bool
		HasTrustDialog bool
		ReadinessSig   string
		TurnDoneSig    string
		TrustKeys      string
		InterruptKey   string
		TypingMinMs    int
	}{
		Agent:          in.Agent,
		PackageName:    in.Agent,
		DisplayName:    displayName,
		ProcessName:    processName,
		GeneratedAt:    time.Now().UTC().Format(time.RFC3339),
		RulesetJSON:    string(rs),
		ProtocolJSON:   string(dp),
		HasReadiness:   gjsonString(dp, "readiness_signal") != "",
		HasTurnDone:    gjsonString(dp, "turn_done_signal") != "",
		HasTrustDialog: gjsonString(dp, "trust_dialog_keys") != "",
		ReadinessSig:   gjsonString(dp, "readiness_signal"),
		TurnDoneSig:    gjsonString(dp, "turn_done_signal"),
		TrustKeys:      gjsonString(dp, "trust_dialog_keys"),
		InterruptKey:   firstNonEmpty(gjsonString(dp, "interrupt_key"), "Escape"),
		TypingMinMs:    gjsonInt(dp, "typing_rhythm_min_ms", 100),
	}

	gens := []struct {
		filename string
		tmpl     string
		mode     os.FileMode
		gofmt    bool
	}{
		{"agent.go", tmplAgent, 0o644, true},
		{"parser.go", tmplParser, 0o644, true},
		{"pid.go", tmplPID, 0o644, true},
		{"classifier_rules.go", tmplClassifierRules, 0o644, true},
		{"parser_test.go", tmplParserTest, 0o644, true},
	}
	for _, g := range gens {
		path := filepath.Join(in.AdapterOutDir, g.filename)
		if err := renderTemplate(path, g.tmpl, data, g.gofmt); err != nil {
			return fmt.Errorf("render %s: %w", g.filename, err)
		}
	}
	// Driver script.
	driverPath := filepath.Join(in.DriverOutDir, "drive-"+in.Agent+"-interactive.sh")
	if err := renderTemplate(driverPath, tmplDriverScript, data, false); err != nil {
		return fmt.Errorf("render driver: %w", err)
	}
	if err := os.Chmod(driverPath, 0o755); err != nil {
		return err
	}
	return nil
}

func renderTemplate(path, tmpl string, data any, gofmt bool) error {
	t, err := template.New(filepath.Base(path)).Parse(tmpl)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	out := buf.Bytes()
	if gofmt {
		formatted, err := format.Source(out)
		if err != nil {
			return fmt.Errorf("gofmt %s: %w\n----\n%s", path, err, out)
		}
		out = formatted
	}
	return os.WriteFile(path, out, 0o644)
}

func readRuleset(path string) (json.RawMessage, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// Compact for embedding.
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		return nil, err
	}
	return json.Marshal(v)
}

func readProtocol(path string) (json.RawMessage, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		return nil, err
	}
	return json.Marshal(v)
}

// gjsonString is a tiny JSON-path accessor used by the template builder.
// json.RawMessage is unmarshaled to map[string]any; we look up dotted
// paths and return the string value (or "").
func gjsonString(raw json.RawMessage, path string) string {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return ""
	}
	parts := strings.Split(path, ".")
	cur := v
	for _, p := range parts {
		m, ok := cur.(map[string]any)
		if !ok {
			return ""
		}
		cur, ok = m[p]
		if !ok {
			return ""
		}
	}
	if s, ok := cur.(string); ok {
		return s
	}
	return ""
}

func gjsonInt(raw json.RawMessage, path string, dflt int) int {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return dflt
	}
	parts := strings.Split(path, ".")
	cur := v
	for _, p := range parts {
		m, ok := cur.(map[string]any)
		if !ok {
			return dflt
		}
		cur, ok = m[p]
		if !ok {
			return dflt
		}
	}
	if f, ok := cur.(float64); ok {
	    return int(f)
	}
	return dflt
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

// Use synth import to make compile-time dep explicit; codegen reads
// synth's output schemas but doesn't call its functions directly today.
var _ = synth.Ruleset{}
