package codegen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"irrlicht/tools/agent-onboarding/internal/groundtruth"
	"irrlicht/tools/agent-onboarding/internal/synth"
)

func TestGenerate_endToEndEmitsCompilableAdapter(t *testing.T) {
	// 1. Stage a tiny synth output by running synth on a synthetic corpus.
	stage := filepath.Join(t.TempDir(), "stage")
	if err := os.MkdirAll(stage, 0o755); err != nil {
		t.Fatal(err)
	}
	prepareSeed(t, stage)

	// 2. Run codegen against the staged outputs.
	adapterDir := filepath.Join(t.TempDir(), "adapter")
	driverDir := filepath.Join(t.TempDir(), "driver")
	err := Generate(Input{
		Agent: "toyagent", StagingDir: stage,
		AdapterOutDir: adapterDir, DriverOutDir: driverDir,
		DisplayName: "Toy Agent", ProcessName: "toyagent",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// 3. Assert the expected files exist.
	expected := []string{
		filepath.Join(adapterDir, "agent.go"),
		filepath.Join(adapterDir, "parser.go"),
		filepath.Join(adapterDir, "pid.go"),
		filepath.Join(adapterDir, "classifier_rules.go"),
		filepath.Join(adapterDir, "parser_test.go"),
		filepath.Join(driverDir, "drive-toyagent-interactive.sh"),
	}
	for _, f := range expected {
		st, err := os.Stat(f)
		if err != nil {
			t.Errorf("missing %s: %v", f, err)
			continue
		}
		if st.Size() == 0 {
			t.Errorf("empty file: %s", f)
		}
	}

	// 4. Sanity-check headers + content.
	b, err := os.ReadFile(filepath.Join(adapterDir, "agent.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "Code generated by agent-onboard gen. DO NOT EDIT.") {
		t.Error("missing generated header in agent.go")
	}
	if !strings.Contains(string(b), `AdapterName = "toyagent"`) {
		t.Errorf("agent.go missing AdapterName const:\n%s", b)
	}

	// 5. Driver script is executable.
	st, _ := os.Stat(filepath.Join(driverDir, "drive-toyagent-interactive.sh"))
	if st != nil && st.Mode().Perm()&0o111 == 0 {
		t.Error("driver script not executable")
	}
}

// TestGenerate_preservesAngleBracketsInPatterns confirms readCompactJSON
// doesn't HTML-escape `<` / `>` / `&` — a regression test for the bug
// where embedded rulesets contained `<proposed_plan>` instead
// of `<proposed_plan>` (legitimate match target for Codex output).
func TestGenerate_preservesAngleBracketsInPatterns(t *testing.T) {
	stage := t.TempDir()
	rs := `{"schema_version":1,"agent":"toy","generated_at":"2026-05-14T00:00:00Z","rules":[
{"rule_id":"x","kind":"transcript_tail_regex","target_state":"working",
 "params":{"pattern":"<proposed_plan>"},"priority":0}]}`
	os.WriteFile(filepath.Join(stage, "ruleset.json"), []byte(rs), 0o644)
	os.WriteFile(filepath.Join(stage, "driver_protocol.json"), []byte(`{"schema_version":1,"agent":"toy"}`), 0o644)

	out := filepath.Join(t.TempDir(), "adapter")
	driver := filepath.Join(t.TempDir(), "driver")
	if err := Generate(Input{Agent: "toy", StagingDir: stage, AdapterOutDir: out, DriverOutDir: driver}); err != nil {
		t.Fatal(err)
	}
	b, _ := os.ReadFile(filepath.Join(out, "classifier_rules.go"))
	// Default json.Marshal HTML-escapes angle brackets into 6-byte unicode
	// escapes. We construct the bad-form sentinels at runtime so the
	// source isn't itself rendered ambiguously by terminal output.
	escapedLT := "\\u00" + "3c"
	escapedGT := "\\u00" + "3e"
	if strings.Contains(string(b), escapedLT) || strings.Contains(string(b), escapedGT) {
		t.Errorf("classifier_rules.go contains \\u-escaped angle brackets — readCompactJSON regression:\n%s", b)
	}
	if !strings.Contains(string(b), "<proposed_plan>") {
		t.Errorf("expected literal <proposed_plan> in classifier_rules.go:\n%s", b)
	}
}

// TestGenerate_handlesBacktickInRulesetParams confirms the codegen survives
// a ruleset.json whose embedded params contain a backtick (which would
// break the legacy `...` raw-string embedding). Synthesis can produce
// such patterns when transcript content uses backticks (markdown code
// fences, shell quoting, etc.).
func TestGenerate_handlesBacktickInRulesetParams(t *testing.T) {
	stage := t.TempDir()
	// Hand-build a ruleset.json containing a backtick in a pattern field.
	rs := `{
  "schema_version": 1,
  "agent": "toy",
  "generated_at": "2026-05-14T00:00:00Z",
  "rules": [
    {"rule_id": "x", "kind": "transcript_tail_regex", "target_state": "ready",
     "params": {"pattern": "code fence ` + "`example`" + ` here"}, "priority": 0}
  ]
}`
	if err := os.WriteFile(filepath.Join(stage, "ruleset.json"), []byte(rs), 0o644); err != nil {
		t.Fatal(err)
	}
	dp := `{"schema_version":1,"agent":"toy"}`
	if err := os.WriteFile(filepath.Join(stage, "driver_protocol.json"), []byte(dp), 0o644); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(t.TempDir(), "adapter")
	driver := filepath.Join(t.TempDir(), "driver")
	err := Generate(Input{Agent: "toy", StagingDir: stage, AdapterOutDir: out, DriverOutDir: driver})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	// The generated classifier_rules.go must parse via go/format.Source
	// (Generate already runs gofmt; a syntax error there would surface as
	// an error). Read it back and confirm the backtick survives.
	b, err := os.ReadFile(filepath.Join(out, "classifier_rules.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "code fence") {
		t.Errorf("backtick-bearing pattern lost from generated source:\n%s", b)
	}
}

// prepareSeed writes a tiny signals.jsonl + ground_truth.jsonl, runs synth,
// and leaves ruleset.json + driver_protocol.json in stage/.
func prepareSeed(t *testing.T, stage string) {
	t.Helper()
	dir := filepath.Dir(stage)
	signals := filepath.Join(dir, "signals.jsonl")
	gt := filepath.Join(dir, "ground_truth.jsonl")

	startTime := time.Date(2026, 5, 14, 12, 0, 0, 0, time.UTC)
	// One signal: a transcript line with stop_reason=end_turn.
	signalsContent := `{"ts":"2026-05-14T12:00:00Z","sensor":"transcript","kind":"line","payload":{"line":"{\"stop_reason\":\"end_turn\"}"}}` + "\n"
	if err := os.WriteFile(signals, []byte(signalsContent), 0o644); err != nil {
		t.Fatal(err)
	}

	meta := groundtruth.Meta{SchemaVersion: 1, Agent: "toyagent", Scenario: "test", RecordingStartedAt: startTime}
	labels := []groundtruth.Label{
		{TsOffsetMs: 0, Marker: "done", ExpectedState: "ready", ToleranceMs: 1000},
	}
	f, _ := os.Create(gt)
	groundtruth.Write(f, meta, labels)
	f.Close()

	if err := synth.Run(context.Background(), synth.Input{
		Agent: "toyagent", Scenario: "test",
		SignalsPath: signals, GroundTruth: gt, StagingDir: stage,
	}); err != nil {
		t.Fatalf("synth setup: %v", err)
	}
}
