package codegen

// Templates for generated adapter files and the driver script. Each
// template is rendered with the same `data` struct (see codegen.go).
// Generated files carry a "Code generated" header so reviewers can
// skip them.

const tmplAgent = `// Code generated by agent-onboard gen. DO NOT EDIT.
// Source: agent={{.Agent}}, generatedAt={{.GeneratedAt}}.
package {{.PackageName}}

import (
	"irrlicht/core/domain/agent"
)

const (
	AdapterName = "{{.Agent}}"
	ProcessName = "{{.ProcessName}}"
)

// Agent returns the generated adapter declaration. Synthesis derived the
// classifier rules and driver protocol from recorded scenarios; the
// embedded ruleset is consumed at runtime by
// core/application/services/rule_evaluator.go via ClassifyStateWithRules.
func Agent() agent.Agent {
	return agent.Agent{
		Identity: agent.Identity{
			Name:        AdapterName,
			DisplayName: "{{.DisplayName}}",
			// Icons are codegen-stubbed; the maintainer should paste real
			// 14×14 SVG markup here after onboarding completes.
			IconSVGLight: ` + "`<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\"></svg>`" + `,
			IconSVGDark:  ` + "`<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\"></svg>`" + `,
		},
		Process: agent.Process{
			Match:         agent.ExactName{Name: ProcessName},
			PIDForSession: DiscoverPID,
		},
		Source: agent.FilesUnderRoot{
			Dir: "",
			Parser: agent.JSONLineParser{
				NewParser: func() agent.LineParser { return &Parser{} },
			},
		},
	}
}
`

const tmplParser = `// Code generated by agent-onboard gen. DO NOT EDIT.
package {{.PackageName}}

import (
	"irrlicht/core/pkg/tailer"
)

// Parser is the minimal TranscriptParser the generated adapter exposes.
// Synthesis derived the agent's transcript shape from recorded scenarios
// but the runtime parser is deliberately format-agnostic — it captures
// the raw line and lets the rule evaluator inspect fields by name. Adapter
// maintainers can extend this struct with format-specific helpers post-
// generation.
type Parser struct{}

// ParseLine implements tailer.TranscriptParser.
func (p *Parser) ParseLine(raw map[string]interface{}) *tailer.ParsedEvent {
	if raw == nil {
		return nil
	}
	return &tailer.ParsedEvent{
		EventType: stringField(raw, "kind"),
	}
}

func stringField(m map[string]interface{}, k string) string {
	if v, ok := m[k].(string); ok {
		return v
	}
	return ""
}
`

const tmplPID = `// Code generated by agent-onboard gen. DO NOT EDIT.
package {{.PackageName}}

import (
	"os/exec"
	"strconv"
	"strings"
)

// DiscoverPID returns the OS PID for the named agent process. The
// generator default is a pgrep-style match against ProcessName; richer
// adapters override this with cwd-based session matching.
func DiscoverPID(sessionID string) (int, error) {
	out, err := exec.Command("pgrep", "-f", ProcessName).Output()
	if err != nil {
		return 0, nil // not running
	}
	line := strings.TrimSpace(string(out))
	if line == "" {
		return 0, nil
	}
	// pgrep may return multiple PIDs; take the first.
	for _, f := range strings.Fields(line) {
		if n, err := strconv.Atoi(f); err == nil {
			return n, nil
		}
	}
	return 0, nil
}
`

const tmplClassifierRules = `// Code generated by agent-onboard gen. DO NOT EDIT.
// Synthesized from scenario recordings on {{.GeneratedAt}}.
package {{.PackageName}}

import (
	"encoding/json"

	"irrlicht/core/application/services"
)

// rulesetJSON is the verbatim ruleset.json the synthesizer produced.
// Embedded as a string so the adapter has zero file-IO at startup.
const rulesetJSON = ` + "`" + `{{.RulesetJSON}}` + "`" + `

// ClassifierRules returns the synthesized classification rules. The
// returned slice is consumed by services.ClassifyStateWithRules at
// runtime; an empty slice (e.g. on synthesis conflict) keeps the legacy
// 4-rule decision tree active.
func ClassifierRules() []services.ClassifierRule {
	var doc struct {
		Rules []services.ClassifierRule ` + "`json:\"rules\"`" + `
	}
	if err := json.Unmarshal([]byte(rulesetJSON), &doc); err != nil {
		return nil
	}
	return doc.Rules
}
`

const tmplParserTest = `// Code generated by agent-onboard gen. DO NOT EDIT.
package {{.PackageName}}

import "testing"

// TestGeneratedParser_doesNotPanic is the smoke test the codegen ships
// with every adapter. It confirms the generated Parser handles nil and
// an empty map without crashing — both are common inputs the tailer
// passes when the agent's transcript stream is half-written.
func TestGeneratedParser_doesNotPanic(t *testing.T) {
	p := &Parser{}
	if e := p.ParseLine(nil); e != nil {
		t.Errorf("nil input should return nil event, got %+v", e)
	}
	if e := p.ParseLine(map[string]interface{}{}); e == nil {
		t.Error("empty map should still produce a (possibly stub) event")
	}
}

// TestGeneratedClassifierRules_parses confirms the embedded ruleset.json
// round-trips into services.ClassifierRule without error. A successful
// parse with zero rules is acceptable — synthesis may have produced an
// empty set on a conflict.
func TestGeneratedClassifierRules_parses(t *testing.T) {
	_ = ClassifierRules()
}
`

const tmplDriverScript = `#!/usr/bin/env bash
# Code generated by agent-onboard gen. DO NOT EDIT.
# Driver protocol for {{.Agent}}, synthesized {{.GeneratedAt}}.
#
# Embedded driver_protocol.json:
# {{.ProtocolJSON}}

set -euo pipefail

PROMPT="${1:-hello}"
SESSION="${2:-onboard-{{.Agent}}-$$}"

# Trust dialog handling — synthesis detected: {{.TrustKeys}}
{{- if .HasTrustDialog}}
TRUST_KEYS="{{.TrustKeys}}"
echo "note: trust dialog detected — driver will send: $TRUST_KEYS" >&2
{{- end}}

# Readiness signal — synthesis detected: {{.ReadinessSig}}
READINESS_SIGNAL="{{.ReadinessSig}}"

# Turn-done signal — synthesis detected: {{.TurnDoneSig}}
TURN_DONE_SIGNAL="{{.TurnDoneSig}}"

# Interrupt key + typing rhythm.
INTERRUPT_KEY="{{.InterruptKey}}"
TYPING_RHYTHM_MS={{.TypingMinMs}}

tmux new-session -d -s "$SESSION" "{{.ProcessName}}" || true
sleep 1

{{if .HasTrustDialog}}
# Trust dialog: send recorded answer.
tmux send-keys -t "$SESSION" "$TRUST_KEYS"
sleep 0.5
{{end}}

# Type the prompt with the synthesized rhythm guard.
for (( i=0; i<${#PROMPT}; i++ )); do
  tmux send-keys -t "$SESSION" "${PROMPT:$i:1}"
  sleep "$(awk -v ms="$TYPING_RHYTHM_MS" 'BEGIN { print ms/1000 }')"
done
tmux send-keys -t "$SESSION" Enter

# Wait for turn-done — substring poll on the live pane.
{{if .HasTurnDone}}
for _ in $(seq 1 120); do
  if tmux capture-pane -p -t "$SESSION" | grep -q "$TURN_DONE_SIGNAL"; then
    break
  fi
  sleep 0.5
done
{{else}}
sleep 30
{{end}}

# Capture final pane for the recorder to read.
tmux capture-pane -p -t "$SESSION"
tmux kill-session -t "$SESSION" 2>/dev/null || true
`
