package etaresearch

import (
	"fmt"
	"strings"
)

// SweepPoint is one (parameter, score) result from a tunable sweep.
type SweepPoint struct {
	Label string
	Score Score
}

// ReportInput is everything RenderReport needs; the caller computes the scores
// and the recommendation so rendering stays pure (no I/O, no wall-clock).
type ReportInput struct {
	Transcripts    int
	Episodes       int
	CleanEpisodes  int
	PriorSeconds   float64
	CorpusNote     string // describes where the corpus came from (fixtures only vs +local)
	Scores         []Score
	BlendSweep     []SweepPoint
	EWMASweep      []SweepPoint
	Recommendation string
}

// RenderReport produces the committed Markdown comparison. Pure: same input →
// same bytes (no timestamps, no randomness), so it is reproducible.
func RenderReport(in ReportInput) string {
	var b strings.Builder
	b.WriteString("# ETA estimator research (#753)\n\n")
	b.WriteString("Replay-based comparison of task-completion ETA estimators. Generated by\n")
	b.WriteString("`tools/eta-research` — re-run with `go run ./cmd/eta-research` (see README).\n")
	b.WriteString("**This file is regenerated, not hand-edited.**\n\n")

	b.WriteString("## Corpus\n\n")
	b.WriteString(in.CorpusNote + "\n\n")
	fmt.Fprintf(&b, "- Transcripts scanned: **%d**\n", in.Transcripts)
	fmt.Fprintf(&b, "- Task episodes segmented: **%d**\n", in.Episodes)
	fmt.Fprintf(&b, "- Episodes that reached completed==total (clean accuracy subset): **%d**\n", in.CleanEpisodes)
	fmt.Fprintf(&b, "- Corpus per-round prior (median seconds/round): **%s**\n\n", fmtDur(in.PriorSeconds))

	b.WriteString("## Approaches\n\n")
	b.WriteString("- **baseline** — current production model: pure observed round-rate, no\n")
	b.WriteString("  estimate until the first round completes (the control).\n")
	b.WriteString("- **prior-bootstrap** — show `total_rounds × prior` at zero rounds, then the\n")
	b.WriteString("  pure observed rate once a round lands (identical to baseline thereafter).\n")
	b.WriteString("- **prior-blend** — Bayesian shrinkage toward the prior at every turn,\n")
	b.WriteString("  `(w·prior + n·observed)/(w+n)`.\n")
	b.WriteString("- **ewma** — exponentially-weighted per-round duration over the marker\n")
	b.WriteString("  history (stateful; shippable only by widening the forecast seam).\n")
	b.WriteString("- **token-aware** — considered and rejected: with no token *budget* target,\n")
	b.WriteString("  remaining-time-from-tokens reduces algebraically to the elapsed round-rate\n")
	b.WriteString("  (`remainingTokens × secsPerToken = (elapsed/completed) × remainingRounds`),\n")
	b.WriteString("  so it adds no signal beyond rounds for *completion-time* prediction.\n\n")

	b.WriteString("## Results\n\n")
	b.WriteString("Accuracy is over turns strictly before the true end. **Latency** columns are\n")
	b.WriteString("the headline for this issue: coverage (fraction of episodes that ever show a\n")
	b.WriteString("number) and seconds-to-first-estimate.\n\n")
	b.WriteString("| approach | MAE | median |err| | median rel | bias | first-est coverage | secs→first | first-est |err| | jitter |\n")
	b.WriteString("|---|--:|--:|--:|--:|--:|--:|--:|--:|\n")
	for _, s := range in.Scores {
		fmt.Fprintf(&b, "| %s | %s | %s | %.0f%% | %s | %.0f%% | %s | %s | %s |\n",
			s.Estimator, fmtDur(s.MAESeconds), fmtDur(s.MedianAbsSeconds), s.MedianRelErr*100,
			fmtSigned(s.BiasSeconds), s.FirstCoverage*100, fmtDur(s.MeanSecsToFirst),
			fmtDur(s.MeanFirstAbsErr), fmtDur(s.MeanJitter))
	}
	b.WriteString("\n")

	if len(in.BlendSweep) > 0 {
		b.WriteString("## Parameter sweep — prior-blend weight `w`\n\n")
		b.WriteString("| w | MAE | median |err| | secs→first |\n|---|--:|--:|--:|\n")
		for _, p := range in.BlendSweep {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", p.Label,
				fmtDur(p.Score.MAESeconds), fmtDur(p.Score.MedianAbsSeconds), fmtDur(p.Score.MeanSecsToFirst))
		}
		b.WriteString("\n")
	}
	if len(in.EWMASweep) > 0 {
		b.WriteString("## Parameter sweep — EWMA `alpha`\n\n")
		b.WriteString("| alpha | MAE | median |err| | jitter |\n|---|--:|--:|--:|\n")
		for _, p := range in.EWMASweep {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", p.Label,
				fmtDur(p.Score.MAESeconds), fmtDur(p.Score.MedianAbsSeconds), fmtDur(p.Score.MeanJitter))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Recommendation\n\n")
	b.WriteString(in.Recommendation + "\n")
	return b.String()
}

func fmtDur(seconds float64) string {
	if seconds == 0 {
		return "0s"
	}
	if seconds < 120 {
		return fmt.Sprintf("%.0fs", seconds)
	}
	return fmt.Sprintf("%.1fm", seconds/60)
}

func fmtSigned(seconds float64) string {
	sign := "+"
	if seconds < 0 {
		sign = "−"
		seconds = -seconds
	}
	return sign + fmtDur(seconds)
}
