package git

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"
	"time"

	"irrlicht/core/internal/costreport"
)

// gitcost_measure_test.go is the generator #1572 asks for on this side: run it
// and it prints the pasteable block behind gitTimeout, gitHistoryTimeout and
// gitMaxOutput.
//
//	IRRLICHT_MEASURE_GIT_COSTS=1 go test ./core/adapters/outbound/git/ \
//	    -run TestMeasureGitCosts -v
//
// It runs in a few seconds against a REAL repository — this one by default,
// IRRLICHT_MEASURE_GIT_REPO to name another — and that is the whole scope
// decision. #1572 is explicitly prophylactic and says "worth doing only if the
// cheap version stays cheap", so what is regenerated here is everything a real
// repository can answer: gitTimeout's three fixed-cost figures, gitMaxOutput's
// bytes-per-commit, and the 3,209-commit point of gitHistoryTimeout's curve.
//
// WHAT IT DELIBERATELY DOES NOT BUILD is the synthetic history behind that
// curve's other two points. #1553 measured those on `git fast-import`
// repositories of 100,000 and 1,000,000 commits, and reproducing them needs
// ~200 lines of stream generation and minutes of machine time per point, for a
// constant chosen against an ORDER OF MAGNITUDE. Rather than omit them — a block
// that quietly stops at what is easy is the failure this package is about — the
// two rows are present and REFUSED by name, so the block says out loud which
// part of the curve it regenerated and which part it did not.
//
// Nothing here modifies the repository it measures: every command is a read, and
// the `tag --contains` subject is resolved rather than created.

const (
	measureGitCostsEnv   = "IRRLICHT_MEASURE_GIT_COSTS"
	measureGitRepoEnv    = "IRRLICHT_MEASURE_GIT_REPO"
	measureGitSamplesEnv = "IRRLICHT_MEASURE_GIT_SAMPLES"

	// fixedCostSamples is for the commands that run in tens of milliseconds.
	fixedCostSamples = 20
	// historyWalkSamples is for the `log` walks, which run in hundreds of
	// milliseconds on this repo and in seconds on a large one. Three rather than
	// twenty because the figure gitHistoryTimeout is argued from is an order of
	// magnitude, and twenty samples of a multi-second walk is precision nobody
	// reads.
	historyWalkSamples = 3
	// grepPatternWithNoMatches is the worst case for `log --all --grep`: git
	// walks every commit looking for matches it never finds, which is the
	// ordinary case for a repo with no reverts and is precisely what
	// gitHistoryTimeout's `--max-count` rejection was measured against.
	grepPatternWithNoMatches = "irrlicht-1572-no-such-trailer"
)

// gitCostPlan is how ONE measured figure is produced, or the named reason this
// machine cannot produce it.
type gitCostPlan struct {
	name string
	note string
	// run performs ONE invocation and returns the bytes of stdout it produced.
	// An error means the invocation did not answer and contributes no sample.
	run func(ctx context.Context) (int, error)
	// samples is how many times run is called.
	samples int
	// population is what the row's bytes-per-commit is divided by, and
	// populationLabel names WHICH population it is. #1553 divided one byte count
	// by the all-refs count for a command that walks HEAD and was ~2.3x low as a
	// result, so a row states the population it used rather than leaving a reader
	// to assume.
	population      int
	populationLabel string
	// unavailable is why this row carries no figure. Non-empty exactly when run
	// is nil.
	unavailable string
}

// TestMeasureGitCosts is the generator. Skipped unless asked for.
func TestMeasureGitCosts(t *testing.T) {
	if os.Getenv(measureGitCostsEnv) == "" {
		t.Skipf("set %s=1 to regenerate the cost figures gitTimeout, gitHistoryTimeout and gitMaxOutput "+
			"are argued from (see costFigureAnchors in gitcost_test.go)", measureGitCostsEnv)
	}
	if gitPath == "" {
		// gitPath is resolved from the trusted path set at package init, so
		// reaching here means there is nothing to measure — stated once rather
		// than left to produce an exec error per row.
		t.Fatal("git could not be resolved from the trusted path set; there is nothing to measure and no figure to print")
	}
	samples := fixedCostSamples
	if raw := os.Getenv(measureGitSamplesEnv); raw != "" {
		n, err := strconv.Atoi(raw)
		if err != nil || n <= 0 {
			t.Fatalf("%s=%q is not a positive integer — refusing rather than silently measuring a default, "+
				"because a figure taken at an n nobody chose is the drift this generator exists to stop",
				measureGitSamplesEnv, raw)
		}
		samples = n
	}

	started := time.Now()
	rows := make([]costreport.Row, 0, 8)
	for _, p := range gitCostPlans(t, samples) {
		rows = append(rows, measureOneGitCost(t, p))
	}
	elapsed := time.Since(started)

	block, err := costreport.Render(
		"outbound/git costs — regenerated by TestMeasureGitCosts (#1572), warm cache",
		[]string{
			fmt.Sprintf("%s/%s, %d CPU, %s, %s; whole run %s",
				runtime.GOOS, runtime.GOARCH, runtime.NumCPU(), runtime.Version(), gitVersion(), elapsed.Round(time.Millisecond)),
			"min is the machine's floor and is the figure to compare across machines: median and p99 move",
			"with whatever else is running, which is why nothing here is a threshold (#1572).",
		},
		rows,
	)
	if err != nil {
		t.Fatalf("%v", err)
	}
	t.Logf("\n\n%s\n", block)
}

// gitCostPlans returns every row of the block: the ones a real repository can
// answer, plus the two curve points it cannot, refused by name.
func gitCostPlans(t *testing.T, samples int) []gitCostPlan {
	t.Helper()
	repo, err := repoUnderMeasurement()
	if err != nil {
		reason := fmt.Sprintf("no repository to measure: %v (set %s to name one)", err, measureGitRepoEnv)
		return append(refusedRows([]string{
			"rev-parse HEAD", "for-each-ref refs/tags", "tag --contains <root>",
			"log --all --grep", "log --pretty=%H %at %s", "log --pretty=%H %at %B",
		}, reason), syntheticCurvePoints()...)
	}
	fromHEAD := countCommits(repo, "--count", "HEAD")
	allRefs := countCommits(repo, "--count", "--all")
	name := filepath.Base(repo)
	scale := fmt.Sprintf("%s, %d commits from HEAD / %d across all refs", name, fromHEAD, allRefs)

	plans := []gitCostPlan{
		{
			name:    "rev-parse HEAD",
			note:    scale,
			samples: samples,
			run:     gitRun(repo, "rev-parse", "HEAD"),
		},
		{
			name:    "for-each-ref refs/tags",
			note:    name,
			samples: samples,
			run:     gitRun(repo, "for-each-ref", "--format=%(refname:short) %(creatordate:iso-strict)", "refs/tags"),
		},
	}
	// `tag --contains` against the ROOT commit is the worst case — every tag
	// contains it — and #1553's own table put this command in the wrong cost
	// class by timing a RECENT commit, which is the cheap case. So the subject is
	// resolved rather than assumed, and a repo whose root cannot be resolved gets
	// a refusal rather than a figure for a different question.
	if root := oldestCommit(repo); root == "" {
		plans = append(plans, gitCostPlan{
			name: "tag --contains <root>",
			unavailable: "could not resolve the root commit reachable from HEAD, so the worst case (every tag contains it) " +
				"cannot be timed — reporting this rather than timing a recent commit, which is the CHEAP case and is how " +
				"#1553's own table put this command in the wrong cost class",
		})
	} else {
		plans = append(plans, gitCostPlan{
			name:    "tag --contains <root>",
			note:    name + ", worst case: every tag contains it",
			samples: samples,
			run:     gitRun(repo, "tag", "--contains", root),
		})
	}

	return append(plans, append([]gitCostPlan{
		{
			name:            "log --all --grep",
			note:            scale + "; worst case (no match), the walk gitHistoryTimeout bounds",
			samples:         historyWalkSamples,
			population:      allRefs,
			populationLabel: "commits across all refs",
			run:             gitRun(repo, "log", "--all", "--grep", grepPatternWithNoMatches, "--pretty=format:%H"),
		},
		{
			name:            "log --pretty=%H %at %s",
			note:            scale + "; CommitsInRange since #1564 — subject only, no body",
			samples:         historyWalkSamples,
			population:      fromHEAD,
			populationLabel: "commits from HEAD",
			run:             gitRun(repo, "log", "--pretty=format:%H %at %s", "HEAD"),
		},
		{
			name:            "log --pretty=%H %at %B",
			note:            scale + "; the body walk gitMaxOutput is argued from",
			samples:         historyWalkSamples,
			population:      fromHEAD,
			populationLabel: "commits from HEAD",
			run:             gitRun(repo, "log", "--pretty=format:%H %at %B", "HEAD"),
		},
	}, syntheticCurvePoints()...)...)
}

// syntheticCurvePoints are gitHistoryTimeout's other two curve points. They are
// present and refused rather than absent, because a block that stops at what is
// easy reads as a complete measurement of a shorter curve.
func syntheticCurvePoints() []gitCostPlan {
	const reason = "needs a synthetic history of that size, which this generator deliberately does not build: ~200 lines of " +
		"`git fast-import` stream generation and minutes per point, for a constant chosen against an order of magnitude " +
		"(#1572's \"worth doing only if the cheap version stays cheap\"). #1553 measured it; re-measure by hand if the " +
		"shape of the curve is ever in doubt"
	return refusedRows([]string{"log walks @ 100,000 commits", "log walks @ 1,000,000 commits"}, reason)
}

func refusedRows(names []string, reason string) []gitCostPlan {
	out := make([]gitCostPlan, 0, len(names))
	for _, n := range names {
		out = append(out, gitCostPlan{name: n, unavailable: reason})
	}
	return out
}

// measureOneGitCost runs one plan and turns it into a row. A call that returned
// an error contributes no sample: the duration of an invocation that did not
// answer is the duration of whatever stopped it, not the cost of the command.
func measureOneGitCost(tb testing.TB, p gitCostPlan) costreport.Row {
	tb.Helper()
	if p.run == nil {
		return costreport.Refused(p.name, p.unavailable)
	}
	ctx := context.Background()
	// One warm-up, discarded: the first walk pages the pack in, and every figure
	// in adapter.go's tables says "warm cache".
	if _, err := p.run(ctx); err != nil {
		return costreport.Refused(p.name, fmt.Sprintf("the warm-up invocation failed: %v", err))
	}
	var (
		ms     []float64
		bytes  int
		failed int
	)
	for i := 0; i < p.samples; i++ {
		start := time.Now()
		n, err := p.run(ctx)
		d := time.Since(start)
		if err != nil {
			failed++
			continue
		}
		bytes = n
		ms = append(ms, float64(d.Nanoseconds())/1e6)
	}
	if len(ms) == 0 {
		return costreport.Refused(p.name, fmt.Sprintf(
			"all %d invocation(s) failed — the duration of a command that did not answer is not its cost, so this row has nothing to report", p.samples))
	}
	note := p.note
	if failed > 0 {
		note += fmt.Sprintf("; %d of %d invocations failed and were discarded", failed, p.samples)
	}
	row := costreport.Measured(p.name, ms, note)
	if p.population > 0 {
		// costreport.WithRate refuses the RATE by name when it cannot be
		// expressed, and never rounds one to zero. That is #1572's own defect:
		// this generator's first draft printed "0 bytes out = 0/commit" for the
		// grep walk and "41 bytes out = 0/commit" for `rev-parse`, both from an
		// integer quotient, in a block that passed.
		row = row.WithRate(bytes, p.population, p.populationLabel)
	}
	return row
}

// gitRun builds a plan's run func. It reads stdout in full rather than through
// the adapter's CappedBuffer, deliberately: gitMaxOutput's table is a statement
// about how many bytes git EMITS, and measuring it through the cap would report
// the cap.
func gitRun(dir string, args ...string) func(context.Context) (int, error) {
	return func(ctx context.Context) (int, error) {
		cmd := exec.CommandContext(ctx, gitPath, args...)
		cmd.Dir = dir
		out, err := cmd.Output()
		if err != nil {
			return 0, err
		}
		return len(out), nil
	}
}

// repoUnderMeasurement resolves the repository the rows run against.
func repoUnderMeasurement() (string, error) {
	if named := os.Getenv(measureGitRepoEnv); named != "" {
		if _, err := os.Stat(filepath.Join(named, ".git")); err != nil {
			// A named repo that is not one is an operator error and must not
			// silently fall back to the cwd — the figure would then describe a
			// repository nobody asked about.
			return "", fmt.Errorf("%s=%q is not a git working tree", measureGitRepoEnv, named)
		}
		return named, nil
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := cwd; ; {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no .git found at or above %s", cwd)
		}
		dir = parent
	}
}

// countCommits reports a rev-list count, so a row carries the population it was
// taken over — the omission that made gitMaxOutput's byte rate 2.3x wrong.
func countCommits(repo string, args ...string) int {
	cmd := exec.Command(gitPath, append([]string{"rev-list"}, args...)...)
	cmd.Dir = repo
	out, err := cmd.Output()
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(out)))
	if err != nil {
		return 0
	}
	return n
}

// oldestCommit resolves the root commit reachable from HEAD — the worst case for
// `tag --contains`. Empty when it cannot be resolved, which the caller reports
// rather than papering over with a recent commit.
func oldestCommit(repo string) string {
	cmd := exec.Command(gitPath, "rev-list", "--max-parents=0", "HEAD")
	cmd.Dir = repo
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	lines := strings.Fields(strings.TrimSpace(string(out)))
	if len(lines) == 0 {
		return ""
	}
	return lines[len(lines)-1]
}

func gitVersion() string {
	out, err := exec.Command(gitPath, "--version").Output()
	if err != nil {
		return "git version unknown"
	}
	return strings.TrimSpace(string(out))
}
