// Rule-based state classifier — alternative path to ClassifyState's hand-coded
// 4-rule decision tree. Adapters generated by `agent-onboard gen` (#268
// Phase 4) export a []ClassifierRule slice plus a matcher; the runtime
// applies them in priority order and returns the first matching state.
//
// Hand-coded legacy adapters (claudecode and friends) continue to use
// ClassifyState as before. Only adapters that opt in by calling
// ClassifyStateWithRules — typically via their generated Agent
// declaration — route through this path.
package services

import (
	"encoding/json"

	"irrlicht/core/domain/session"
)

// ClassifierRule is the runtime representation of one synthesized rule.
// Generated adapters export a []ClassifierRule from their classifier_rules.go.
// The Kind / Params shape mirrors tools/agent-onboarding/internal/rulelib so
// that synthesis output can round-trip into adapter code without a transform.
type ClassifierRule struct {
	RuleID      string          `json:"rule_id"`
	Kind        string          `json:"kind"`
	TargetState string          `json:"target_state"`
	Params      json.RawMessage `json:"params"`
	Priority    int             `json:"priority"`
}

// Evidence is what the rule evaluator returns alongside the chosen state.
// Phase 7's viewer reads it to render the "why did the state change?"
// panel. It is intentionally small: rule id + a free-form one-liner
// pointing at the firing signal.
type Evidence struct {
	RuleID    string `json:"rule_id,omitempty"`
	Detail    string `json:"detail,omitempty"`
	SignalRef string `json:"signal_ref,omitempty"`
}

// EvalContext is the input each rule evaluates against. For now it is
// metrics-derived; richer per-signal context (last pane snapshot, last
// hook fire, etc.) can land here as adapters need it.
type EvalContext struct {
	Metrics      *session.SessionMetrics
	LastEventTxt string // last transcript line text, if any
}

// EvaluateRules walks rules in priority order and returns the first rule
// whose state implication is consistent with the current EvalContext. If
// no rule applies, returns (currentState, zero Evidence, false) so the
// caller can fall back to the legacy decision tree.
//
// The evaluator's match logic is deliberately limited to metrics-derived
// signals in Phase 4. The richer per-Kind matching documented in the
// synth-time rulelib package is exercised by the validator and viewer,
// which have full access to the raw signals.jsonl. The runtime evaluator
// runs inside the live daemon and only sees aggregated session metrics —
// so it implements the Kinds that are derivable from SessionMetrics.
func EvaluateRules(rules []ClassifierRule, currentState string, ec EvalContext) (string, Evidence, bool) {
	if ec.Metrics == nil || len(rules) == 0 {
		return currentState, Evidence{}, false
	}
	for _, r := range rules {
		if matchRuntime(r, ec) {
			return r.TargetState, Evidence{
				RuleID: r.RuleID,
				Detail: r.Kind + " matched",
			}, true
		}
	}
	return currentState, Evidence{}, false
}

// matchRuntime evaluates a rule against EvalContext. Kinds that need
// per-signal evidence (pane snapshots, network probes, etc.) are skipped
// at runtime — the validator catches those via signals.jsonl replay.
func matchRuntime(r ClassifierRule, ec EvalContext) bool {
	switch r.Kind {
	case "transcript_field_value":
		var p struct {
			Field string `json:"field"`
			Value string `json:"value"`
		}
		if err := json.Unmarshal(r.Params, &p); err != nil {
			return false
		}
		// Heuristic mapping over SessionMetrics. The synthesizer's most
		// common emit is `stop_reason=end_turn` for ready and similar
		// for working; we approximate by checking IsAgentDone.
		if ec.Metrics == nil {
			return false
		}
		if p.Field == "stop_reason" && p.Value == "end_turn" {
			return ec.Metrics.IsAgentDone()
		}
		if p.Field == "event_msg.type" && p.Value == "task_complete" {
			return ec.Metrics.IsAgentDone()
		}
		return false

	case "interrupt_marker":
		// Match if the metrics record a user interrupt or tool denial in
		// the most-recent pass.
		if ec.Metrics == nil {
			return false
		}
		return ec.Metrics.LastWasUserInterrupt || ec.Metrics.LastWasToolDenial

	case "hook_fired":
		// Adapter wired its own hook signal into SessionMetrics.PermissionPending.
		if ec.Metrics == nil {
			return false
		}
		return ec.Metrics.PermissionPending
	}
	return false
}

// ClassifyStateWithRules is the rule-aware entry point. If rules is
// non-nil and any rule fires, its target state and evidence win.
// Otherwise this falls through to the legacy ClassifyState path so the
// caller's existing semantics are preserved for non-rule adapters.
//
// Callers (typically the SessionDetector or replay harness, once
// adapters are regenerated to expose ClassifierRules()) pass the rules
// slice their adapter exposes; legacy adapters pass nil.
func ClassifyStateWithRules(
	currentState string,
	metrics *session.SessionMetrics,
	rules []ClassifierRule,
) (string, string, Evidence) {
	if len(rules) > 0 {
		if newState, ev, ok := EvaluateRules(rules, currentState, EvalContext{Metrics: metrics}); ok {
			if newState != currentState {
				return newState, ev.RuleID + ": " + ev.Detail, ev
			}
			return currentState, "", ev
		}
	}
	st, reason := ClassifyState(currentState, metrics)
	return st, reason, Evidence{}
}
